apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-hello-{{ .Values.source.targetRevision}}
  annotations: 
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # The project the application belongs to.
  project: default
  # Source of the application manifests
  source:
    repoURL: {{ .Values.source.repoURL }}
    targetRevision: {{ .Values.source.targetRevision}}
    path: helm/go-hello
    helm:
      releaseName: qa
   
    # plugin:
    #   name: argocd-vault-plugin-helm
  # Destination cluster and namespace to deploy the application
  destination:
    server: {{ .Values.destination.server }}
    namespace: {{.Values.destination.namespace }}

  # Sync policy
  syncPolicy:
    syncOptions:
      - CreateNamespace=true  
    automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
  