apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-react-app-{{ .Values.source.targetRevision}}
  annotations: 
    # notifications.argoproj.io/subscribe.on-sync-succeeded.gmail: khinnandartun1818@gmail.com
    # notifications.argoproj.io/subscribe.on-sync-status-unknown.gmail: khinnandartun1818@gmail.com
    # notifications.argoproj.io/subscribe.on-deleted.gmail: khinnandartun1818@gmail.com
    # notifications.argoproj.io/subscribe.on-sync-succeeded.grafana: tag1
    # notifications.argoproj.io/subscribe.on-sync-status-unknown.grafana: tag1
    # notifications.argoproj.io/subscribe.on-sync-status-unknown.webhook-golang: ""
  # You'll usually want to add your resources to the argocd namespace.
  # Add a this finalizer ONLY if you want these to cascade delete.
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # The project the application belongs to.
  project: default
  plugin:
    name: argocd-vault-plugin

  # Source of the application manifests
  source:
    repoURL: {{ .Values.source.repoURL }}
    targetRevision: {{ .Values.source.targetRevision}}
    path: helm/my-react-app
    helm:
      releaseName: qa
   
  # Destination cluster and namespace to deploy the application
  destination:
    server: {{ .Values.destination.server }}
    namespace: {{.Values.destination.namespace }}

  # Sync policy
  syncPolicy:
    syncOptions:
      - CreateNamespace=true  
    automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
  